import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstakQueryProvider from "@/components/partials/provider/TanstakQueryProvider";
import Header from "@/components/partials/Header";
import Footer from "@/components/partials/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstakQueryProvider>
          <Header />
          {children}
          <Footer />
        </TanstakQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
